global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "daily_yt_album_bot_bot"
    static_configs:
      - targets:
          - "bot-app:8000"
        labels:
          app: "daily_yt_album_bot"
          component: "bot"
  - job_name: "daily_yt_album_bot_worker"
    static_configs:
      - targets:
          - "worker:8001"
        labels:
          app: "daily_yt_album_bot"
          component: "worker"
